# Generated by Django 5.2 on 2025-11-23 07:03

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('traffic', '0005_devicetoken_savedroute'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='devicetoken',
            options={},
        ),
        migrations.AlterModelOptions(
            name='savedroute',
            options={'ordering': ['-saved_at']},
        ),
        migrations.RenameField(
            model_name='savedroute',
            old_name='distance',
            new_name='duration_text',
        ),
        migrations.RenameField(
            model_name='savedroute',
            old_name='last_checked_at',
            new_name='last_checked',
        ),
        migrations.RenameField(
            model_name='savedroute',
            old_name='selected_routes',
            new_name='raw_selected_routes',
        ),
        migrations.RenameField(
            model_name='savedroute',
            old_name='created_at',
            new_name='saved_at',
        ),
        migrations.RemoveField(
            model_name='devicetoken',
            name='username',
        ),
        migrations.RemoveField(
            model_name='savedroute',
            name='duration',
        ),
        migrations.RemoveField(
            model_name='savedroute',
            name='username',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='first_ip',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='first_user_agent',
        ),
        migrations.AddField(
            model_name='devicetoken',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='device_token', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='savedroute',
            name='alert_enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='savedroute',
            name='distance_km',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='savedroute',
            name='last_checked_duration',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='savedroute',
            name='polyline_data',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='savedroute',
            name='route_id',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AddField(
            model_name='savedroute',
            name='user',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='saved_routes', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userprofile',
            name='fcm_token',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='phone_number',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='savedroute',
            name='alert_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='savedroute',
            name='leaving_time',
            field=models.TimeField(),
        ),
        migrations.CreateModel(
            name='RouteAlternative',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alt_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('summary', models.CharField(blank=True, max_length=255)),
                ('distance_km', models.FloatField(blank=True, null=True)),
                ('duration_text', models.CharField(blank=True, max_length=100)),
                ('polyline_data', models.TextField(blank=True)),
                ('saved_route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alternatives', to='traffic.savedroute')),
            ],
        ),
        migrations.CreateModel(
            name='TrafficCheckLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('log_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('checked_at', models.DateTimeField(auto_now_add=True)),
                ('old_duration', models.IntegerField(blank=True, null=True)),
                ('new_duration', models.IntegerField(blank=True, null=True)),
                ('diff_seconds', models.IntegerField(blank=True, null=True)),
                ('congestion_flag', models.BooleanField(default=False)),
                ('api_response_snippet', models.TextField(blank=True)),
                ('saved_route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='check_logs', to='traffic.savedroute')),
            ],
            options={
                'ordering': ['-checked_at'],
            },
        ),
    ]
