# Generated by Django 5.2 on 2025-11-23 07:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('traffic', '0006_alter_devicetoken_options_alter_savedroute_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='savedroute',
            options={'ordering': ['-timestamp']},
        ),
        migrations.RenameField(
            model_name='savedroute',
            old_name='saved_at',
            new_name='timestamp',
        ),
        migrations.RemoveField(
            model_name='savedroute',
            name='distance_km',
        ),
        migrations.RemoveField(
            model_name='savedroute',
            name='duration_text',
        ),
        migrations.AddField(
            model_name='savedroute',
            name='distance',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='savedroute',
            name='duration',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='savedroute',
            name='username',
            field=models.CharField(blank=True, db_index=True, max_length=150),
        ),
        migrations.AlterField(
            model_name='savedroute',
            name='alert_time',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='savedroute',
            name='leaving_time',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='savedroute',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='saved_routes', to=settings.AUTH_USER_MODEL),
        ),
    ]
