# Generated by Django 5.2 on 2025-11-23 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('traffic', '0007_alter_savedroute_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='savedroute',
            options={'ordering': ['-created_at']},
        ),
        migrations.RenameField(
            model_name='savedroute',
            old_name='timestamp',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='savedroute',
            old_name='raw_selected_routes',
            new_name='selected_routes',
        ),
        migrations.RemoveField(
            model_name='savedroute',
            name='distance',
        ),
        migrations.RemoveField(
            model_name='savedroute',
            name='duration',
        ),
        migrations.RemoveField(
            model_name='savedroute',
            name='polyline_data',
        ),
        migrations.AddField(
            model_name='savedroute',
            name='distance_km',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='savedroute',
            name='duration_text',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='savedroute',
            name='polyline',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='savedroute',
            name='alert_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='savedroute',
            name='leaving_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
