# Generated by Django 5.2 on 2025-11-23 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('traffic', '0008_alter_savedroute_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='savedroute',
            name='alert_status',
            field=models.CharField(default='pending', max_length=32),
        ),
        migrations.AddField(
            model_name='savedroute',
            name='last_alert_sent',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
