# Generated by Django 5.2 on 2025-11-23 17:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('traffic', '0009_savedroute_alert_status_savedroute_last_alert_sent'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserFcmDevice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fcm_token', models.TextField()),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fcm_devices', to='traffic.userprofile')),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
    ]
