# Generated by Django 5.2 on 2025-11-25 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('traffic', '0011_trafficalert'),
    ]

    operations = [
        migrations.AlterField(
            model_name='savedroute',
            name='alert_time',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
    ]
