# Generated by Django 5.2 on 2025-11-25 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('traffic', '0012_alter_savedroute_alert_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='trafficalert',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='trafficalert',
            name='destination',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='trafficalert',
            name='origin',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='savedroute',
            name='alert_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='trafficalert',
            name='message',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='trafficalert',
            name='severity',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='trafficalert',
            name='title',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
